# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AuthFirebase' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AuthFirebase

  target 'AuthFirebase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AuthFirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

